---
version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./chat-app-backend
    command: >
      gunicorn --bind 0.0.0.0:8000 --reload backend.wsgi
    volumes:
      - web-static:/code/static
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
  nginx:
    build: ./nginx
    volumes:
      - web-static:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  frontend:
    build: ./chat-app-frontend
    command: yarn serve
    volumes:
      - ./chat-app-frontend:/code
    expose:
      - 8080
    depends_on:
      - db
      - backend

volumes:
  postgres_data:
  web-static:
