version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./chat-app-backend
    command: python manage.py runserver 0:8000
    volumes:
      - ./chat-app-backend/backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
