version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./chat-app-backend
    volumes:
      - ./chat-app-backend/backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./chat-app-frontend
    command: yarn serve
    volumes:
      - ./chat-app-frontend:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - backend

volumes:
  postgres_data:
