---
version: '3.4'

services:
  db:
    ports:
      - 5432:5432
  backend:
    entrypoint: >
      gunicorn --bind 0.0.0.0:8000 --reload backend.wsgi
    command: ''
    volumes:
      - ./chat-app-backend/backend:/code
    environment:
      - DJANGO_DEBUG=True
      - DATABASE=postgres
      - DJANGO_ALLOWED_HOSTS=www.chat-app.com,127.0.0.1,localhost,0.0.0.0
    ports:
      - 3001:8000
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  frontend:
    command: yarn serve
    image: chat_app_frontend:dev
    build:
      target: build
    volumes:
      - ./chat-app-frontend:/code
    ports:
      - 3002:8080
    environment:
      - NODE_ENV='development'
