---
version: '3.4'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./chat-app-backend
    entrypoint: >
      daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - web-static:/code/static
    expose:
      - 8000
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    env_file: chat-app-backend/env
  nginx:
    build: ./nginx
    volumes:
      - web-static:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  frontend:
    build:
      context: ./chat-app-frontend
    volumes:
      - node_modules:/code/node_modules
    expose:
      - 8080
    depends_on:
      - db
      - backend
  redis:
    image: redis:5
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  web-static:
  node_modules:
