---
version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./chat-app-backend
    volumes:
      - ./chat-app-backend/backend:/code
      - web-static:/code/static
    ports:
      - 8000
    depends_on:
      - db
  backend-static:
    build: ./chat-app-backend-static
    volumes:
      - web-static:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - backend
  frontend:
    build: ./chat-app-frontend
    command: yarn serve
    volumes:
      - ./chat-app-frontend:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - backend

volumes:
  postgres_data:
  web-static:
