# Generated by Django 3.0.4 on 2020-03-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(auto_now=True, verbose_name='creation time'),
        ),
    ]
